// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ResetBtn = NULL;
lv_obj_t * ui_Speed = NULL;
lv_obj_t * ui_ConsumpAvg = NULL;
lv_obj_t * ui_Distance = NULL;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_Fuel = NULL;
lv_obj_t * ui_Consump = NULL;
lv_obj_t * ui_Date = NULL;
lv_obj_t * ui_Reset = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResetBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ResetBtn, 75);
    lv_obj_set_height(ui_ResetBtn, 40);
    lv_obj_set_x(ui_ResetBtn, 100);
    lv_obj_set_y(ui_ResetBtn, 85);
    lv_obj_set_align(ui_ResetBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed, 0);
    lv_obj_set_y(ui_Speed, -15);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "0 km/h");
    lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsumpAvg = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ConsumpAvg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConsumpAvg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConsumpAvg, -100);
    lv_obj_set_y(ui_ConsumpAvg, 50);
    lv_obj_set_align(ui_ConsumpAvg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConsumpAvg, "0 l/100km");

    ui_Distance = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Distance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Distance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distance, 100);
    lv_obj_set_y(ui_Distance, 20);
    lv_obj_set_align(ui_Distance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distance, "0 km");

    ui_Time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 0);
    lv_obj_set_y(ui_Time, -90);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "12:34");
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fuel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Fuel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fuel, 100);
    lv_obj_set_y(ui_Fuel, 50);
    lv_obj_set_align(ui_Fuel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fuel, "0 l");

    ui_Consump = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Consump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Consump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Consump, -100);
    lv_obj_set_y(ui_Consump, 20);
    lv_obj_set_align(ui_Consump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Consump, "0 l/100km");

    ui_Date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 0);
    lv_obj_set_y(ui_Date, -65);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "01.01.2026");

    ui_Reset = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Reset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Reset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Reset, 100);
    lv_obj_set_y(ui_Reset, 85);
    lv_obj_set_align(ui_Reset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Reset, "Reset");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ResetBtn = NULL;
    ui_Speed = NULL;
    ui_ConsumpAvg = NULL;
    ui_Distance = NULL;
    ui_Time = NULL;
    ui_Fuel = NULL;
    ui_Consump = NULL;
    ui_Date = NULL;
    ui_Reset = NULL;

}
