// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_ResetBtn(lv_event_t * e);
extern lv_obj_t * ui_ResetBtn;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_ConsumpAvg;
extern lv_obj_t * ui_Distance;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Fuel;
extern lv_obj_t * ui_Consump;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Reset;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern bool reset;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

